when_release: &when_release
  when:
    ref:
      - refs/tags/v*

when_stage: &when_stage
  when:
    ref:
      include:
        - refs/heads/main
      exclude:
        - refs/tags/v*

when_dev: &when_dev
  when:
    ref:
      exclude:
        - refs/tags/v*
        - refs/heads/main

kind: pipeline
type: docker
name: default

steps:
  - name: confluent-oss-4.1.4_prod
    image: plugins/docker
    settings:
      dockerfile: confluent-oss-4.1.4/Dockerfile
      username: karimlamouri
      password:
        from_secret: docker_password
      repo: karimlamouri/confluent-oss-4.1.4
      tags:
        - latest
        - ${DRONE_TAG##v}
    <<: *when_release

  - name: confluent-oss-4.1.4_stage
    image: plugins/docker
    settings:
      dockerfile: confluent-oss-4.1.4/Dockerfile
      username: karimlamouri
      password:
        from_secret: docker_password
      repo: karimlamouri/confluent-oss-4.1.4
      tags:
        - stage
    <<: *when_stage

  - name: confluent-oss-4.1.4_dev
    image: plugins/docker
    settings:
      dockerfile: confluent-oss-4.1.4/Dockerfile
      username: karimlamouri
      password:
        from_secret: docker_password
      repo: karimlamouri/confluent-oss-4.1.4
      tags:
        - SNAPSHOT-${DRONE_BRANCH}
    <<: *when_dev

  - name: terraform-0.11.14-terragrunt-0.18.7_dev
    image: plugins/docker
    settings:
      dockerfile: terraform-0.11.14-terragrunt-0.18.7/Dockerfile
      username: karimlamouri
      password:
        from_secret: docker_password
      repo: karimlamouri/terraform-0.11.14-terragrunt-0.18.7
      tags:
        - SNAPSHOT-${DRONE_BRANCH}
    <<: *when_dev

  - name: terraform-0.11.14-terragrunt-0.18.7_prod
    image: plugins/docker
    settings:
      dockerfile: terraform-0.11.14-terragrunt-0.18.7/Dockerfile
      username: karimlamouri
      password:
        from_secret: docker_password
      repo: karimlamouri/terraform-0.11.14-terragrunt-0.18.7
      tags:
        - latest
        - ${DRONE_TAG##v}
    <<: *when_release

  - name: terraform-0.11.14-terragrunt-0.18.7_stage
    image: plugins/docker
    settings:
      dockerfile: terraform-0.11.14-terragrunt-0.18.7/Dockerfile
      username: karimlamouri
      password:
        from_secret: docker_password
      repo: karimlamouri/terraform-0.11.14-terragrunt-0.18.7
      tags:
        - stage
    <<: *when_stage
